# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Grafica Publicar

on:
  push:
    branches: [ "grafica-publicar" ]
  pull_request:
    branches: [ "grafica-publicar" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
        #cache-dependency-path: './package-lock.json'
    - run: npm install
    - run:  REACT_APP_API_ROOT='https://api.graficapublicar.com.ar' npm run build --if-present
    - name: SCP Files
      uses: cross-the-world/scp-pipeline@b4d86397129250eb940fabdc3f7a435436d2503a
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        local: "build/"
        remote: "/usr/local/lsws/grafica-publicar/html/imprenta-frontend"      
